Add Homework4_ChangeMaxMinValues
ValeriaFom/WexAutoTraining pull request #4
Opened 2022-04-01 20:47 UTC by ValeriaFom

Homework 4
1.Создать два произвольных массива, подсчитать максимальное  и минимальное значение их элементов. Вывести на экран.
2.Поменять в массивах максимальные и минимальные значения местами.

@EgorAntonovich, please review my Homework 4.

2022-04-12 19:38 UTC, EgorAntonovich requested changes

2022-04-12 19:38 UTC, EgorAntonovich commented on Homework4/Program.cs
> +            int minValue = array1[0];
Please create function for find min/max and use it

2022-04-12 19:38 UTC, EgorAntonovich commented on Homework4/Program.cs
> +            int oldMinPlace = array1[minPlace];
Please develop function for swap values

2022-04-12 19:38 UTC, EgorAntonovich commented on Homework4/Program.cs
> +            int[] array2 = { 98465, 3, 0, -45, 1568 };
please create function for init array

2022-04-12 19:39 UTC, EgorAntonovich requested changes
Fix comments

2022-05-11 20:14 UTC, ValeriaFom commented
I've committed fixes. Please, review.

2022-08-12 12:21 UTC, merged