Add Homework6_AbstractClassAndMethod
ValeriaFom/WexAutoTraining pull request #6
Opened 2022-04-01 21:08 UTC by ValeriaFom

Homework 6.
1.Создать абстрактный класс Покупатель, у которого есть абстрактный метод Оплатить. 
2.Создать наследников от этого класса-Покупатель за наличные, покупатель с дебетовой картой, и покупатель с кредитной картой.
3.Реализовать в них метод Оплатить(пусть просто выводит на экран способ оплаты)
4.Создать массив из 5 покупателей разного типа, и в цикле вызвать метод Оплатить. Проверить что каждый оплатил своим способом(сообщения на экране)

@EgorAntonovich, please review my Homework 6.

2022-04-12 19:45 UTC, EgorAntonovich requested changes

2022-04-12 19:45 UTC, EgorAntonovich commented on Homework6/CustomersWithPaymentMethod.cs
> +    class CustomerWithCash : Customer
In .Net we consider that for every class we create new file. Please use this code way.

2022-04-13 21:05 UTC, ValeriaFom commented on Homework6/CustomersWithPaymentMethod.cs
> +    class CustomerWithCash : Customer
Fixed. Thank you

2022-04-20 09:35 UTC, EgorAntonovich approved these changes

2022-05-11 20:17 UTC, merged